### Get All Moods
GET http://localhost:8080/api/moods
Accept: application/json

### Get a Mood
@get_id = 363bc126-79ba-431b-a9ad-d56cf1463a71
GET http://localhost:8080/api/moods/{{get_id}}
Accept: application/json

### Get Statistics
GET http://localhost:8080/api/moods/statistics
Accept: application/json

### Save a Mood
POST http://localhost:8080/api/moods
Content-Type: application/json

{
  "value": 2,
  "note": "feeling very sad",
  "date": "2026-04-27T12:12:12"
}

### Save a Mood
POST http://localhost:8080/api/moods
Content-Type: application/json

{
  "value": 5,
  "note": "feeling somewhat better but still sad"
}

### Save a Mood
POST http://localhost:8080/api/moods
Content-Type: application/json

{
  "value": 8,
  "note": "felling good now",
  "date": "2026-04-29T10:58:13"
}

### Delete a Mood
@delete_id = 2069fb1f-1386-403c-9df0-eaeab4c30a78
DELETE http://localhost:8080/api/moods/{{delete_id}}
Accept: application/json