server.port=${SERVER_PORT:8081}

spring.application.name=moody-backend
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:moody}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driverClassName=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}

spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.H2Dialect}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.generate-ddl=true

spring.web.error.include-message=always
spring.jpa.open-in-view=false
spring.ai.ollama.base-url=${SPRING_AI_OLLAMA_BASE_URL:http://localhost:11434}
spring.ai.ollama.chat.model=${SPRING_AI_OLLAMA_CHAT_MODEL:llama3}